### ISSUE TITLE
MMM-Futar can't start

### ISSUE THREAD

**Issue by fenyvesi** [balassy/MMM-Futar#32]
I just installed the MagicMirror latest version and can't start the module. (I can use it with an older MM version on another machine).

Do you have any clue what to do?
Thanks.
George

P.S. Egyébként kiváló a modul.

The PM2 error message is the following:
`/home/orangepi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
[01.08.2023 20:40.59.847] [ERROR] (node:3893) UnhandledPromiseRejectionWarning: Error: Cannot find module 'request'
Require stack:
- /home/orangepi/MagicMirror/modules/MMM-Futar/node_helper.js
- /home/orangepi/MagicMirror/js/app.js
- /home/orangepi/MagicMirror/js/electron.js
- /home/orangepi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117457)
    at Module._resolveFilename (/home/orangepi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/orangepi/MagicMirror/modules/MMM-Futar/node_helper.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadModule (/home/orangepi/MagicMirror/js/app.js:180:19)
(Use `electron --trace-warnings ...` to show where the warning was created)
[01.08.2023 20:40.59.848] [ERROR] (node:3893) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[3893:0801/204100.116285:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3893:0801/204100.116748:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3923:0801/204100.587537:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization`

**Comment by fenyvesi** [comment]
I know that the constant complaints of the users are boring and disturbing but is there any chance to modify the source?

If not,  I clear the MM-Futar with bleeding heart.

Köszi.

**Comment by fenyvesi** [comment]
Just for the record:

I managed the solve the problem. Although it can happen that there is a better solution, but it works for me.

So the main problem was the missing key: sometime in the past it became a must.

1. You should acquire a key on the page: https://opendata.bkk.hu/keys
Let's suppose that your key value is KEY_VALUE.

2. Stop MM.
3. Modify the .../MagicMriror/modules/MMM-FUTAR/node-helper.js file line 37. Be cautious with the apostrophs, you can't see here: (`) !!!

const url = `https://futar.bkk.hu/api/query/v1/ws/otp/api/where/arrivals-and-departures-for-stop.json?stopId=${config.stopId}&onlyDepartures=true&minutesBefore=0&minutesAfter=${config.minutesAfter}&key=KEY_VALUE`;

3. start MM.

**Comment by balassy** [comment]
Thanks for reporting this issue. I've released version 2.0.1 that already has build-in support for API Keys with the new `apiKey` configuration parameter that should fix this issue.
